<?php 

        //Copmposer generated autoload.php file.
        require 'vendor/autoload.php';
        
        //Create PHPMailer class.
        use PHPMailer\PHPMailer\PHPMailer;

        //Connect to the database.
        include('config/db_connect.php');
        
        //If form has been submitted.
        if(isset($_POST['contactFrmSubmit'])){

            //Protection from SQLInjection.
            $first_name = mysqli_real_escape_string($conn, $_POST['first_name']);
            $last_name = mysqli_real_escape_string($conn, $_POST['last_name']);
            $email = mysqli_real_escape_string($conn, $_POST['email']);
            $company_name = mysqli_real_escape_string($conn, $_POST['company_name']);
            $client_message = mysqli_real_escape_string($conn, $_POST['client_message']);        

            //sql insert
            $sql = "INSERT INTO potential_clients(first_name, last_name, email, company_name, client_message) VALUES('$first_name', '$last_name', '$email', '$company_name', '$client_message')";

            //Save to db and check.
            if(mysqli_query($conn, $sql)){
                //Send message to email with client info.
                //Create a PHPMailer object.
                $mail = new PHPMailer();

                //PHPMailer SMTP configuration.
                $mail->isSMTP();
                $mail->Host = 'smtp.mailtrap.io';
                $mail->SMTPAuth = true;
                $mail->Username = '25bdb3243d5d56'; //paste one generated by Mailtrap
                $mail->Password = '307e08b471abe0'; //paste one generated by Mailtrap
                $mail->SMTPSecure = 'tls';
                $mail->Port = 2525;

                //Specify PHPMailer headers
                $mail->setFrom($email, 'Mailtrap');
                $mail->addReplyTo('info@mailtrap.io', 'Mailtrap');
                $mail->addAddress('recipient1@mailtrap.io', 'Tim'); 
                $mail->addCC('cc1@example.com', 'Elena');
                $mail->addBCC('bcc1@example.com', 'Alex');

                //Mail subject.
                $mail->Subject = 'New Potential Client';

                //Set the email format to HTML
                $mail->isHTML(true);

                //Input the desired content.
                $mailContent = "<h3>Congratulations Micheal, you have a new potential client!</h3>
                <p>Client Name: " . $first_name . " " . $last_name . "</br></p>
                <p>Company Name: " . $company_name . "</br></p>
                <p>Message: " . $client_message . "</br></p>";

                $mail->Body = $mailContent;

                if($mail->send()){
                    echo 'Message has been sent';
                }else{
                    echo 'Message could not be sent.';
                    echo 'Mailer Error: ' . $mail->ErrorInfo;
                }

            }else{
                echo "query error ".mysqli_error($conn);
            }

        }
?>

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Main Feed</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="static/style.css?v=1.1">

        <!-- Bootstrap CDN -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
        <!-- Google Fonts API -->
        <link href="https://fonts.googleapis.com/css2?family=Recursive&display=swap" rel="stylesheet">

        <!--Google Fonts: Dancing Script-->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">

    </head>
  